wooga/atlas-version

src/integrationTest/groovy/wooga/gradle/version/VersionPluginIntegrationSpec.groovy
src/main/groovy/wooga/gradle/version/VersionPlugin.groovy
src/main/groovy/wooga/gradle/version/VersionPluginExtension.groovy
src/main/groovy/wooga/gradle/version/internal/DefaultVersionPluginExtension.groovy
src/main/groovy/wooga/gradle/version/internal/release/base/DefaultVersionStrategy.groovy
src/main/groovy/wooga/gradle/version/internal/release/base/ReleaseVersion.groovy
src/main/groovy/wooga/gradle/version/internal/release/base/TagStrategy.groovy
src/main/groovy/wooga/gradle/version/internal/release/base/VersionStrategy.groovy
src/main/groovy/wooga/gradle/version/internal/release/opinion/Strategies.groovy
src/main/groovy/wooga/gradle/version/internal/release/opinion/package-info.groovy
src/main/groovy/wooga/gradle/version/internal/release/semver/ChangeScope.groovy
src/main/groovy/wooga/gradle/version/internal/release/semver/NearestVersion.groovy
src/main/groovy/wooga/gradle/version/internal/release/semver/NearestVersionLocator.groovy
src/main/groovy/wooga/gradle/version/internal/release/semver/PartialSemVerStrategy.groovy
src/main/groovy/wooga/gradle/version/internal/release/semver/SemVerStrategy.groovy
src/main/groovy/wooga/gradle/version/internal/release/semver/SemVerStrategyState.groovy
src/main/groovy/wooga/gradle/version/internal/release/semver/StrategyUtil.groovy
src/main/groovy/wooga/gradle/version/internal/release/semver/package-info.groovy
src/main/groovy/wooga/gradle/version/strategies/NetflixOssStrategies.groovy
src/main/groovy/wooga/gradle/version/strategies/SemverV1Strategies.groovy
src/main/groovy/wooga/gradle/version/strategies/SemverV2Strategies.groovy

The forked sources of both nebular release and gradle-git create no problems in this project setup. When running the plugin it can happen that the original sources are called which are not API complained. I moved all forked sources into a new package.
* ![IMPROVE] change package name of forked sources
[NEW]:https://atlas-resources.wooga.com/icons/icon_new.svg "New"
[ADD]:http://resources.atlas.wooga.com/icons/icon_add.svg "Add"
[IMPROVE]:http://resources.atlas.wooga.com/icons/icon_improve.svg "IMPROVE"
[CHANGE]:http://resources.atlas.wooga.com/icons/icon_change.svg "Change"
[FIX]:http://resources.atlas.wooga.com/icons/icon_fix.svg "Fix"
[UPDATE]:http://resources.atlas.wooga.com/icons/icon_update.svg "Update"
[BREAK]:http://resources.atlas.wooga.com/icons/icon_break.svg "Remove" …

Change package name of forked source to reduce clashes

---

src/integrationTest/groovy/wooga/gradle/version/IntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/version/VersionPluginIntegrationSpec.groovy
src/main/groovy/wooga/gradle/version/VersionConsts.groovy
src/main/groovy/wooga/gradle/version/VersionPlugin.groovy
src/main/groovy/wooga/gradle/version/VersionPluginExtension.groovy
src/main/groovy/wooga/gradle/version/VersionScheme.groovy
src/main/groovy/wooga/gradle/version/internal/DefaultVersionPluginExtension.groovy
src/main/groovy/wooga/gradle/version/internal/MemoisationProvider.groovy
src/main/groovy/wooga/gradle/version/internal/ToStringProvider.groovy
src/test/groovy/wooga/gradle/version/VersionPluginSpec.groovy
src/test/groovy/wooga/gradle/version/internal/MemoisationProviderSpec.groovy
src/test/groovy/wooga/gradle/version/internal/ToStringProviderSpec.groovy

This is a small cleanup patch to prepare the next `versionCode` implementation. I renamed the extension property `scheme` to `versionScheme` and also adjusted the type to an enum `VersionScheme`. I left the ability to set this value from `String` to make it easier to set the value in the `build.gradle` script.
I wrapped the version provider in a new custom provider which can cache the infered value. This whole provider gets wrapped again in a special `ToStringProvider`. This providers `toString` method will evaluate the internal value and call `toString` on it. The default `Provider` instances only provide a basic `toString` implementation.
I also added more test cases for the new APIs and classes
* ![CHANGE] `scheme` to `versionScheme`
* ![CHANGE] `versionScheme` type from `String` to …

Refactor version provider

---

src/integrationTest/groovy/wooga/gradle/version/IntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/version/VersionPluginIntegrationSpec.groovy
src/main/groovy/wooga/gradle/version/VersionCodeExtension.groovy
src/main/groovy/wooga/gradle/version/VersionCodeScheme.groovy
src/main/groovy/wooga/gradle/version/VersionConsts.groovy
src/main/groovy/wooga/gradle/version/VersionPlugin.groovy
src/main/groovy/wooga/gradle/version/VersionPluginExtension.groovy
src/main/groovy/wooga/gradle/version/internal/DefaultVersionCodeExtension.groovy
src/main/groovy/wooga/gradle/version/internal/DefaultVersionPluginExtension.groovy
src/main/groovy/wooga/gradle/version/internal/VersionCode.groovy
src/main/groovy/wooga/gradle/version/internal/release/base/TagStrategy.groovy
src/test/groovy/wooga/gradle/version/VersionPluginSpec.groovy
src/test/groovy/wooga/gradle/version/internal/VersionCodeSpec.groovy

This patch adds multiple schemes to generate or manual set a versionCode. The strategies differ in two major ways:
A strategy based on a `semver` version number. This patch provides two `schemes` to generate a version code from a given semver version string:
This scheme turns a semver version `major.minor.patch` into a integer representation. Everything after the components is ignored. The version components are not allowed to be higher than `99` This means that the biggest version provided possible is `99.99.99`. The resulting code is an integer with padded values.
`1.0.0`   => `10000`
`1.1.1`   => `10101`
`1.11.10` => `11110`
The `semver` scheme is an opinionated addon to the `semverBasic` scheme. The resulting code is extended by a revision counter. This counter has only one digit so …

Add versionCode generation

---

src/main/groovy/wooga/gradle/version/internal/release/base/TagStrategy.groovy
src/test/groovy/wooga/gradle/version/VersionPluginSpec.groovy

With the patch [#7] I added a regression. Because of a type I disabled parsing of tags without a prefix `v`. I had no tests in place for this behavior so this ended up in the latest `rc` build [v0.1.0-rc.4].
My intention was to set the new added field `parseVersionsWithoutPrefixV` to true for the default constructor. Instead I picked the groovy generated `field` for the `setPrefixNameWithV` (`prefixNameWithV`).
I fixed the issue and added a small set of regression tests.
* ![FIX] `TagStrategy` tag prefix parsing default value
[#7]:  https://github.com/wooga/atlas-version/pull/7
[v0.1.0-rc.4]: https://github.com/wooga/atlas-version/releases/tag/v0.1.0-rc.4
[NEW]:https://atlas-resources.wooga.com/icons/icon_new.svg "New"
[ADD]:https://atlas-resources.wooga.com/icons/icon_add.svg "Add" …

Fix TagStrategy tag prefix parsing default value

---

src/integrationTest/groovy/wooga/gradle/version/VersionPluginIntegrationSpec.groovy
src/main/groovy/wooga/gradle/version/VersionConsts.groovy
src/main/groovy/wooga/gradle/version/VersionPluginExtension.groovy
src/main/groovy/wooga/gradle/version/VersionScheme.groovy
src/main/groovy/wooga/gradle/version/internal/DefaultVersionPluginExtension.groovy
src/main/groovy/wooga/gradle/version/internal/release/base/MarkerTagStrategy.groovy
src/main/groovy/wooga/gradle/version/internal/release/opinion/Strategies.groovy
src/main/groovy/wooga/gradle/version/internal/release/semver/SemVerStrategy.groovy
src/main/groovy/wooga/gradle/version/internal/release/semver/SemVerStrategyState.groovy
src/main/groovy/wooga/gradle/version/strategies/SemverV1Strategies.groovy
src/main/groovy/wooga/gradle/version/strategies/StaticMarkerStrategies.groovy
src/test/groovy/wooga/gradle/version/VersionPluginSpec.groovy

This new strategy won't auto increment the normal part of the version as `semver` or `semver2` would do. Instead the whole normal part of the version is taken from a `marker` tag. Other metadata information for prerelease versions are generated in a similar fashion than done in the `semver` strategies but not based on the latest release tag but also on the marker tag.
One can define two marker tags in the project.
* `ci-0.0.0`
* `release-0.0.0`
The prefix can not be configured at the moment. The version strategy will look for these markers and determine the normal of the generated version. We have two different markers depending on the current release cycle. We can configure to use a specific marker based on the current git branch. This can be configured with the `releaseBranchPattern` …

Add new strategy staticMarker

---

build.gradle

This patch updates `grgit-core` to patch `4.1.1` which limits the version range of `jgit` to latest major version `5`. This allows this plugin to be used with jdk8 still. I also had to add an force resolution of `grgit-core:4.1.1` because the buildscript pulls a version of this plugin into the classpath. This should later be saved to remove
* ![FIX] `jgit` jdk8 compatibility issue
[UPDATE]: …

Fix jgit jdk8 compatibility issue

---

build.gradle
src/integrationTest/groovy/wooga/gradle/version/VersionIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/version/VersionPluginIntegrationSpec.groovy
src/main/groovy/wooga/gradle/version/ReleaseStage.groovy
src/main/groovy/wooga/gradle/version/VersionPluginConventions.groovy
src/main/groovy/wooga/gradle/version/VersionPluginExtension.groovy
src/main/groovy/wooga/gradle/version/internal/DefaultVersionPluginExtension.groovy
src/main/groovy/wooga/gradle/version/internal/release/base/VersionStrategy.groovy
src/main/groovy/wooga/gradle/version/internal/release/opinion/Strategies.groovy
src/main/groovy/wooga/gradle/version/internal/release/semver/SemVerStrategy.groovy
src/main/groovy/wooga/gradle/version/strategies/SemverV2Strategies.groovy

Add helper methods to get the release stage (dev, rc, snapshot, final). This is useful for writing predicates and the like.
* ![ADD] Providers in the extension to get the current release stage resolved by the plugin.
[REMOVE]: …

Add helper methods to get the release stage

---

src/main/groovy/wooga/gradle/version/ReleaseStage.groovy
src/main/groovy/wooga/gradle/version/VersionScheme.groovy
src/main/groovy/wooga/gradle/version/internal/DefaultVersionPluginExtension.groovy
src/main/groovy/wooga/gradle/version/internal/release/opinion/Strategies.groovy
src/main/groovy/wooga/gradle/version/strategies/SemverV1Strategies.groovy
src/main/groovy/wooga/gradle/version/strategies/WdkStrategies.groovy
src/test/groovy/wooga/gradle/version/VersionPluginSpec.groovy

Adds a custom "preflight" stage to be used mainly for integration testing before a more format pre-release.
* ![ADD] Add a custom wdk strategy, which contains the newer preflight stage
* ![ADD] Add some helpers to generate the preflight release
[REMOVE]: …

Add a "preflight" release stage [ATLAS-646]

---

src/main/groovy/wooga/gradle/version/ReleaseStage.groovy
src/main/groovy/wooga/gradle/version/VersionScheme.groovy
src/main/groovy/wooga/gradle/version/internal/DefaultVersionPluginExtension.groovy
src/main/groovy/wooga/gradle/version/internal/release/opinion/Strategies.groovy
src/main/groovy/wooga/gradle/version/strategies/SemverV1Strategies.groovy
src/main/groovy/wooga/gradle/version/strategies/WdkStrategies.groovy
src/test/groovy/wooga/gradle/version/VersionPluginSpec.groovy

Adds a custom "preflight" stage to be used mainly for integration testing before a more format pre-release.
* ![ADD] Add a custom wdk strategy, which contains the newer preflight stage
* ![ADD] Add some helpers to generate the preflight release
[REMOVE]: …

Add prefight release stage

---

Jenkinsfile
build.gradle

This patch adds snyk monitoring to the build pipeline. It will hook itself into the check and publish stages.
The patch also sets a dependency helper plugin net.wooga.cve-dependency-resolution which applies overrides for dependencies with know fixes for security issues.
* ![ADD] `snyk` monitoring
* ![ADD] `net.wooga.snyk-wdk-java` snyk convention plugin
* ![ADD] `net.wogoa.cve-dependency-resolution` plugin
[NEW]:https://atlas-resources.wooga.com/icons/icon_new.svg "New"
[ADD]:http://resources.atlas.wooga.com/icons/icon_add.svg "Add"
[IMPROVE]:http://resources.atlas.wooga.com/icons/icon_improve.svg "IMPROVE"
[CHANGE]:http://resources.atlas.wooga.com/icons/icon_change.svg "Change"
[FIX]:http://resources.atlas.wooga.com/icons/icon_fix.svg "Fix" …

Add snyk integration [ATLAS-712]

---

.github/PULL_REQUEST_TEMPLATE.md
.github/SUPPORT.md
Jenkinsfile
build.gradle

Because of security issues reported for the coveralls gradle plugin I decided to remove the feature during build. It is not enough to just stop sending reports via jenkins. We also need to update to `net.wooga.plugins` > `4.0.0` because this version removes the dependency.
I remove the coveralls token in the Jenkinsfile so our base pipeline won't try to call the coveralls task on the gradle project.
* ![UPDATE] `net.wooga.plugins` to version `4.0.0` to remove coveralls dependency
* ![REMOVE] coveralls token in Jenkinsfile
[CHANGE]: …

Remove coveralls reporting [ATLAS-764]

---

src/main/groovy/wooga/gradle/version/internal/release/semver/NearestVersion.groovy
src/main/groovy/wooga/gradle/version/internal/release/semver/NearestVersionLocator.groovy
src/main/groovy/wooga/gradle/version/internal/release/semver/SemVerStrategy.groovy
src/test/groovy/wooga/gradle/version/VersionPluginSpec.groovy

The `previousVersion` field from Extension's `version` property returned `"0.0.0"` on cases where it couldn't find a previous version (ie. there are no version git tags in the git repository). This causes problems when integrating with other plugins. For instance, `GithubRelease` in atlas-github tries to find the "0.0.0" and crashes in the process. 
To better reflect the lack of previous version tags, `previousVersion` is now set to `null` when this case happens. Several tests were also updated to cover cases for generating version when there are no git version tags present.
* ![IMPROVE] `version.previousVersion` now is `null` instead of `"0.0.0"` when there are no version tags.
[ADD]: …

Previous version property is null when there isn't any version tag on git

---

src/main/groovy/wooga/gradle/version/VersionScheme.groovy
src/main/groovy/wooga/gradle/version/strategies/NewSemverV1Strategies.groovy
src/main/groovy/wooga/gradle/version/strategies/NewSemverV2Strategies.groovy
src/main/groovy/wooga/gradle/version/strategies/opinion/UpmStrategies.groovy
src/test/groovy/wooga/gradle/version/NewSemverV1StrategySpec.groovy
src/test/groovy/wooga/gradle/version/NewSemverV2StrategySpec.groovy
src/test/groovy/wooga/gradle/version/UPMStrategySpec.groovy
src/test/groovy/wooga/gradle/version/VersionPluginSpec.groovy

Created new strategy aggregator class `UPMStrategies`, containing strategies related to UPM packages.
Those new UPM Strategies are based on SemverV2 Strategies (`NewSemverV2Strategies`), plus a pre-flight stage that is a SemverV2-equivalent of the pre-flight stage of WDK Strategies, and a default stage that is the same of current `LegacyNugetStrategies` in order to keep versions consistent in case of those two strategies being used in the same project tree.
* ![ADD] New Strategies for UPM projects, `UPMStrategies`
* ![ADD] Tests for `UPMStrategies`, `NewSemverV1Strategies` `NewSemverV2Strategies`
[IMPROVE]: …

Added upm strategies and tests for new Strategies 

---

src/integrationTest/groovy/wooga/gradle/version/VersionPluginExtensionIntegrationSpec.groovy
src/main/groovy/wooga/gradle/version/internal/DefaultVersionPluginExtension.groovy
src/test/groovy/wooga/gradle/version/VersionPluginSpec.groovy

On the previous refactor the release scope now maps to the ChangeScope enum. Thing is, support for empty release scopes passed through command line  wasn't present, which is a bug, and it wasn't covered by tests. 
* ![FIX] `-Prelease.scope` did not support empty values. …

Fix bug where plugin breaks on empty scope

---

src/main/groovy/wooga/gradle/version/internal/release/semver/SemVerStrategy.groovy
src/test/groovy/wooga/gradle/version/internal/SemVerStrategySpec.groovy

Adds a log info message that details the repository staged/unstaged sets if the repository is found dirty. This is to help debug when it is do during builds.
* ![ADD] `SemVerStrategy` log for repository status when found dirty
[REMOVE]: …

Add a log entry detailing the repository status if it's found dirty

---

src/integrationTest/groovy/wooga/gradle/version/VersionIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/version/VersionPluginIntegrationSpec.groovy
src/main/groovy/wooga/gradle/version/VersionCodeScheme.groovy
src/main/groovy/wooga/gradle/version/VersionPlugin.groovy
src/main/groovy/wooga/gradle/version/VersionPluginConventions.groovy
src/main/groovy/wooga/gradle/version/VersionPluginExtension.groovy
src/main/groovy/wooga/gradle/version/VersionScheme.java
src/main/groovy/wooga/gradle/version/VersionSchemes.groovy
src/main/groovy/wooga/gradle/version/internal/DefaultVersionPluginExtension.groovy
src/main/groovy/wooga/gradle/version/internal/GitStrategyPicker.groovy
src/main/groovy/wooga/gradle/version/internal/VersionCode.groovy
src/main/groovy/wooga/gradle/version/internal/release/base/PrefixVersionParser.groovy
src/main/groovy/wooga/gradle/version/internal/release/base/VersionParser.groovy
src/main/groovy/wooga/gradle/version/internal/release/git/GitVersionRepository.groovy
src/main/groovy/wooga/gradle/version/internal/release/git/TagStrategy.groovy
src/main/groovy/wooga/gradle/version/strategies/NewSemverV1Strategies.groovy
src/main/groovy/wooga/gradle/version/strategies/NewSemverV2Strategies.groovy
src/test/groovy/wooga/gradle/version/NewSemverV1StrategySpec.groovy
src/test/groovy/wooga/gradle/version/NewSemverV2StrategySpec.groovy
src/test/groovy/wooga/gradle/version/VersionPluginSpec.groovy
src/test/groovy/wooga/gradle/version/internal/VersionCodeSpec.groovy

Smaller changes that are too small for their own single PR. Described below:
* Removes `generate` param from VersionCodeScheme. It wasn't being used internally anymore, but class is not internal, so this was being kept for backwards compatibility sake.
* Renames `TagStrategy`and related classes to `VersionParser` and similar. There is a meaning overload in the `Strategy` word, as its also used to describe the many kinds of versions (semver, semver2, etc). Parser describes better what this class family does (*parse* a raw tag name to a internal version object).
* Coalesces old `MarkerTagStrategy` and `TagStrategy` into a single `PrefixVersionParser`, as both dealt with prefixes.
* Also, `VersionParser` now receives a String instead of a `Tag`, to make it detached from git concepts.
Based …

Smaller pending breaking change refactors

---

src/integrationTest/groovy/wooga/gradle/version/VersionIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/version/VersionPluginIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/version/VersionPluginMultiProjectIntegrationSpec.groovy
src/main/groovy/wooga/gradle/version/VersionCodeSchemes.groovy
src/main/groovy/wooga/gradle/version/VersionPlugin.groovy
src/main/groovy/wooga/gradle/version/VersionPluginConventions.groovy
src/main/groovy/wooga/gradle/version/VersionPluginExtension.groovy
src/main/groovy/wooga/gradle/version/VersionScheme.java
src/main/groovy/wooga/gradle/version/internal/DefaultVersionCodeExtension.groovy
src/test/groovy/wooga/gradle/version/VersionPluginSpec.groovy

This plugin is no longer limited to the root project. On each project the plugin applies its version to all its child projects. This way, child projects without the plugin receives the version of the nearest parent with an applied plugin. 
For instance, in the example below, `projectA`, `subproject2` and `projectC` don't apply `net.wooga.version`, so their version are determined by the closest parent who does. 
```
rootProject applies v4.0.0      -> rootProject.version == 4.0.0
├── subproject1 applies v1.0.0  -> subproject1.version == 1.0.0
│   ├── projectA (no apply)     -> projectA.version == subproject1.version == 1.0.0
│   └── projectB applies v0.0.1 -> projectB.version == 0.0.1
└── subproject2 (no apply)      -> subproject2.version == rootProject.version == 4.0.0
├── projectC (no …
```

Enable use in subprojects

---

src/integrationTest/groovy/wooga/gradle/version/VersionPluginMultiProjectIntegrationSpec.groovy
src/main/groovy/wooga/gradle/version/VersionPluginExtension.groovy

FIxes bug where `versionBuilder.setScope` wont recognize a scope when its used with a lower-case string. 
* ![FIX] `versionBuilder.setScope` now recognizes both upper and lower cases.
[REMOVE]:   https://resources.atlas.wooga.com/icons/icon_remove.svg "Remove"
[IOS]: …

normalizes setScope(string) to be case unsensitive

---

src/main/groovy/wooga/gradle/version/VersionPluginExtension.groovy
src/test/groovy/wooga/gradle/version/VersionPluginSpec.groovy

Previous major `is<Stage>` extension methods were not matching 100% the release stage so they were put to private and only were used in the internals of the extension. 
However, those methods are still useful, and are being an annoying source breaks elsewhere. Adding them back with a correct implementation gives us back some useful methods, and reduce pains on the 2.x-3.x jump.
* ![ADD] `isSnapshot`, `isDevelopment`, `isPrerelease` and `isFinal` extension methods.
[FIX]: …

Make is<Stage> public

---

src/main/groovy/wooga/gradle/version/VersionPlugin.groovy

Memoize the project version provider, which was currently being invoked... repeatedly. 
* ![ADD] `VersionPlugin` now memoizes the version provider set on the projects
[REMOVE]:   https://resources.atlas.wooga.com/icons/icon_remove.svg "Remove"
[IOS]: …

Memoize the project version provider
